# Generated by Django 6.0.1 on 2026-01-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, choices=[('HR', 'Hr'), ('Engineering', 'Engineering'), ('Sales', 'Sales'), ('NA', 'Na')], max_length=15)),
                ('role', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Manager', 'Manager'), ('Analyst', 'Analyst'), ('NA', 'Na')], max_length=15)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
